# profiles/slurm/config.yaml
executor: slurm
jobs: 320
default-resources:
  - slurm_partition=earth-3
  - slurm_qos=earth-3.test
  - slurm_time="1-00:00:00"
  - slurm_extra="--constraint=rhel8"
  - mem_mb=4096
  - threads=1
default-group-jobs: 1
latency-wait: 60
restart-times: 1
max-jobs-per-second: 10
local-cores: 1
config:
  env: "hpc"

