# profiles/slurm/config.yaml
jobs: 320
cluster:
  mkdir -p logs/slurm/{rule} &&
  sbatch
    --partition=earth-3
    --qos=earth-3.1d
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time=1-00:00:00
    --constraint=rhel8
    --job-name=smk-{rule}
    --output=logs/slurm/{rule}/%j-{rule}.out
    --error=logs/slurm/{rule}/%j-{rule}.err
    --parsable
default-resources:
  - threads=1
  - mem_mb=4096
config:
  env: "hpc"
restart-times: 1
max-jobs-per-second: 10
latency-wait: 60
local-cores: 1
